chore: Expand `centre` to allow for title line options

diff --git a/configuration/local-bin/.local/bin/centre b/configuration/local-bin/.local/bin/centre
--- a/configuration/local-bin/.local/bin/centre
+++ b/configuration/local-bin/.local/bin/centre
@@ -1,3 +1,82 @@
 #!/usr/bin/env bash
 
-fmt -c -w $(tput cols)
+# NAME
+#   centre - little helper to centre a line of text in a terminal
+#
+# SYNOPSIS
+#   seq 10 | centre [--help]
+#
+# DESCRIPTION
+#   --help,-h  = Print this usage
+#
+# DEPENDENCIES
+#   - tput
+#   - fmt
+
+set -o nounset
+set -o errexit
+set -o pipefail
+#set -o xtrace
+
+function Main() {
+  local format=plain
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+      --help|-h) Usage && exit 0 ;;
+      *) Error "Unknown option: $1" ;;
+    esac
+    shift
+  done
+
+  case "$format" in
+    plain) Plain "$@" ;;
+  esac
+}
+
+function Plain() {
+  fmt -c -w $(tput cols)
+}
+
+function Usage() {
+  sed -E -f <(GetSection "UsageSedScript") $0
+}
+
+function Error() {
+  echo "ERROR: $@" >&2
+  echo >&2
+  Usage >&2
+  exit 1
+}
+
+# Utils
+
+# Get a delimited section of this file
+function GetSection() {
+  local section="$1"
+  sed -En "/^#.*${section}:Start/,/^#.*${section}:End/ { s/^# ?//; p; }" $0 | sed '1d; $d'
+}
+
+# Entry point
+
+Main "$@"
+
+exit 0
+
+# NOTE: The rest of this file is not executed, so can hold scripts for
+# different languages etc.  Use `GetSection xxx` to obtain the text for a
+# particular section.
+
+#~~~~~~~~~~~~~~~~~~~~UsageSedScript:Start~~~~~~~~~~~~~~~~~~~~
+# #n
+# /^#!/ n
+# /^#/ {
+#   :heading
+#   /^#/ {
+#     s/^# ?//
+#     p
+#     n
+#     b heading
+#   }
+#   q
+# }
+#~~~~~~~~~~~~~~~~~~~~~UsageSedScript:End~~~~~~~~~~~~~~~~~~~~~
